
node {


       stage('Checkout'){

         echo 'checkout'
       }

       stage('Test'){
	   
		 echo 'test'
		 
       }

       stage('Deploy'){

         echo 'Push to Repo'

         echo 'ssh to web server and tell it to pull new image'

       } 

}